name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        default: '1.0.0-preview1'
      packageSource:
        description: 'Package source'
        required: true
        default: 'https://api.nuget.org/v3/index.json'

env:
  Version: ${{ github.event.inputs.releaseVersion }}
  PackageVersion: ${{ github.event.inputs.releaseVersion }}

jobs:
  verify:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100
    - name: Test
      run: dotnet test --verbosity normal

  release_zip:
    needs: verify
    name: Release BaGetter.zip to GitHub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100
    - name: Publish
      run: dotnet publish src/BaGetter --configuration Release --output artifacts
    - name: Upload
      uses: actions/upload-artifact@v3.1.3
      with:
        name: BaGetter
        path: artifacts

  release_docker_image:
    needs: verify
    name: Release Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.0.0

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        push: true
        tags: |
          jefersonjr/bagetter:latest
          jefersonjr/bagetter:${{ github.event.inputs.releaseVersion }}
